networks:
  interweb:

services:
  fe:
    build: ./fe
    ports:
      - "5002:5000"
    volumes:
      - ./fe/app:/app
    environment:
      - FLASK_APP=__init__.py
      - FLASK_ENV=development
    networks:
      - interweb

  users-service:
    build: ./users-service
    ports:
      - "5001:5000"
    volumes:
      - ./users-service/app:/app
    depends_on:
      - users-db
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    networks:
      - interweb

  order-service:
    build: ./order-service
    ports:
      - "5004:5000"
    volumes:
      - ./order-service/app:/app
    depends_on:
      - order_service_db
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    networks:
      - interweb

  order_service_db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_service_db
    ports:
      - "5434:5432"
    volumes:
      - orders-data:/var/lib/postgresql/data
    networks:
      - interweb
      
  users-db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - users-data:/var/lib/postgresql/data
    networks:
      - interweb

volumes:
  users-data:
  orders-data:
