"""Add menu_item_names column

Revision ID: 1ee3df02b172
Revises: 6abc831595a5
Create Date: 2025-01-11 22:06:01.166089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee3df02b172'
down_revision = '6abc831595a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_items_names', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('menu_items_names')

    # ### end Alembic commands ###
